name: test
on:
  push:
    branches:
      - "*"
jobs:
  testBullFrog:
    runs-on: ubuntu-latest
    steps:
      - name: Set up bullfrog to block everything except *.github.com
        uses: bullfrogsec/bullfrog@1472c28724ef13ea0adc54d0a42c2853d42786b1 # v0.8.2
        with:
           egress-policy: block
           allowed-domains: |
             *.github.com

      - name: Try making outbound connection (bypass)
        run: |
          python3 bypass.py  # This runs the script that exfiltrates data via allowed domains
